### ISSUE TITLE
Which was the last version of papaermerge-core which supported folder sharing among different users?

### ISSUE THREAD

**Issue by freakster00** [papermerge/papermerge-core#131]

**Comment by ciur** [comment]
[Version 2.0.1](https://github.com/papermerge/papermerge-core/releases/tag/v2.0.1)

**Comment by freakster00** [comment]
Does it give restful endpoints?

**Comment by ciur** [comment]
No. Or to be exact just couple of them (very very limited).
https://docs.papermerge.io/2.0.0/User%27s%20Manual/rest_api.html
The full documentation for that version is:

https://docs.papermerge.io/2.0.0/index.html

Papermerge 2.1.x is almost a complete rewrite of 2.0.x. In other words, they are entirely different applications. They just look same, a called same and sort of versioning implies as 2.1. is continuation of 2.0... which is not true. As I mentioned before, 2.1 is a complete rewrite of 2.0.

**Comment by freakster00** [comment]
![image](https://user-images.githubusercontent.com/121386692/226102930-9e2cdfe0-4c57-44e3-ba6b-d6ef2f87dd94.png)
What is the best way to run this locally i dont see any manage.py?

**Comment by ciur** [comment]
In branch stable/2.0.x papermerge-core is a plain django app (i.e. no manage.py).
The django project itself (manage.py file plus base urls.py, wsgi.py file etc) are in branch stable/2.0.x of the ciur/papermerge repository.
here https://github.com/ciur/papermerge/tree/stable/2.0.x.
So, for that branch you need to use both repositories. This is because initially project was hosted in ciur/papermerge repo and migrated to this repository only later.
