### ISSUE TITLE
Docker container start fail: "exec /run.bash: exec format error"

### ISSUE THREAD

**Issue by pagnotta** [papermerge/papermerge-core#25]
I followed instructions from https://docs.papermerge.io/Installation/docker.html to setup Papermerge on 

- RPi4
- Ubuntu Server 20.04.4 LTS (GNU/Linux 5.4.0-1065-raspi aarch64)
- Docker 20.10.17
- Docker Compose v2.6.0

using the [docker-compose.yml](https://raw.githubusercontent.com/papermerge/papermerge-core/master/docker/docker-compose.yml) from the documentation.

When starting with `docker compose -f docker-compose.yml --env-file .env up` the frontend, worker, ws and backend containers fail with a

`exec /run.bash: exec format error`

![image](https://user-images.githubusercontent.com/16732021/173086620-28e672f8-7993-453c-8d94-99238257069c.png)

A `docker logs papermerge-frontend-1` delivers 

`exec /usr/sbin/nginx: exec format error`,

all other failed containers

`exec /run.bash: exec format error`.

The other containers (like traefik, pg, ...) are starting up fine. When trying to load Papermerge in the browser I get a `404 page not found`, presumably deliverd by traefik which can't find the papermerge containers.

Anybody knows this issue? Any hints? Thanks.

**Comment by pagnotta** [comment]
I have a feeling it might be due to arm architecture?

**Comment by ciur** [comment]
I googled it and I found this [stack overflow answer](https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error) which suggests that problem indeed may be because of different cpu architecture your are trying to run on.

Just to confirm that, you may try to rebuild [frontend docker image](https://github.com/papermerge/papermerge.js#docker-image) (the easiest one to rebuild), change docker compose to use your docker image for frontend and see if it fixes at least frontend part (given the fact that traefik is up and running you at very least will be able to see the login view in the browser).

**Comment by ciur** [comment]
Closing ticket due to lack of activity.
