### ISSUE TITLE
What is considered a Release Candidate when using docker-compose?

### ISSUE THREAD

**Issue by SgtKilgore406** [papermerge/papermerge-core#37]
Following the documentation for setting up Papermerge via docker-compose I am confused as to what version of the software is considered to be a stable release candidate.

The link to the GitHub Packages list shows all the versions are labeled as alpha or "a". Coupled with the warning "Currently docker tag latest points to latest 2.1.0-alphaXYZ version which is not yet production ready." leaves me confused as to how I should interpret the stable releases when none of them have release candidate or "rc" associated with them.

The rest of the documentation is easy to follow but I would like some suggestions as to what should be consider as stable for the fresh install and moving forward.

**Comment by ciur** [comment]
@SgtKilgore406 

There is no stable release yet for version 2.1, and as such, there is no release candidate yet; 2.1 is still work in progress and it is in alpha stage (meants that not all features were yet implemented + there are some critical bugs).

Regarding "2.1.0-alphaXYZ"  vs "a" they mean same thing - alpha stage.
Initially I tagged versions is  2.1.0-alpha1, 2.1.0-alpha2,... This pattern I borrowed from [https://semver.org/](https://semver.org/).
Later, however, I learned that [python way of tagging pre-releases](https://peps.python.org/pep-0440/#pre-releases) is with "a" instead of "alpha" and I switched to python way of tagging releases - thus alpha versions are now tagged with 2.1.0a1, 2.1.0a2, 2.1.0a3 etc.

Following features are still missing for in 2.1
- show OCRed text
- documents merging
- show matching context in search drop down (search dropdown shows only matched documents, and not what text matched)

The plan is to release first beta version i.e 2.1b1 (feature complete, but still buggy) in September 2022 and first release candidate i.e. 2.1rc1 in October 2022.

**Comment by SgtKilgore406** [comment]
Okay, so is there a version of Papermerge for docker-compose in general that is considered stable? I am arguably a noob at GitHub but I do understand the alpha, beta, release candidate concepts.

I have browsed the Versions list on GitHub, according to the documentation link here (https://github.com/orgs/papermerge/packages) but only the Alpha 2.1 versions are listed.

If I go to the general releases page I can see (https://github.com/papermerge/papermerge-core/releases/) v2.0.0 and the release candidates leading up to it. However if I try assigning 2.0 or 2.0.0 to the APP_TAG line in the .env file Docker errors out with unknown manifest.

I guess my primary question at this time is do you have a stable release version for Docker or do I need to download the v2.0.0 source and build from that?

Thank you in advance for the quick initial reply.

**Comment by SgtKilgore406** [comment]
Please disregard my last comment. I'll go ahead and use the current Alpha build and consider the server as a testing environment until the first release candidate is available.

I am looking for a good replacement for LogicalDoc DMS. That system has a nasty habit of disconnecting the DB with no surefire solution to fix it. Tried out Docspell but the lack of user administration is a deal breaker. I have high hopes for Papermerge and look forward to using it in the future.

Once release candidates are available for Docker I will probably start donating to help further the development. I am not a developer but would be able to help with donations.
