### ISSUE TITLE
Unknown command: 'worker'. 

### ISSUE THREAD

**Issue by luyuanerp** [papermerge/papermerge-core#50]
After installing according to the Contributor's Manual document, the following problems occur

1. run the ./manage.py worker step,
The following error message appears。
Unknown command: 'worker'.
<img width="896" alt="0" src="https://user-images.githubusercontent.com/75401343/186151683-995845a2-5731-4836-aa95-c0b31c401619.png">

2. The backend and frontend starts normally, but the front-end page cannot be accessed. The chrome console prompts an error as shown below。
<img width="1309" alt="5" src="https://user-images.githubusercontent.com/75401343/186153281-46925ae9-aab0-49f2-b884-cb74edc464cf.png">

Backend startup screenshot
<img width="1111" alt="1" src="https://user-images.githubusercontent.com/75401343/186152314-154e2b95-975a-4643-b688-60506649ff8f.png">

Frontend startup screenshot
<img width="954" alt="2" src="https://user-images.githubusercontent.com/75401343/186152368-1969b1b0-fd78-4672-8c7c-5b4d3d04ad17.png">

Please help to see, thanks.

**Comment by ciur** [comment]
this command was removed

>  ./manage.py worker 

now you can start worker with (just make sure you start command from ./docker/dev folder):

`poetry run task worker
`

Regarding the frontend issue, I see that you access it from external IP (120.76.102.100:4200), in such case it won't work, because, in development mode, the frontend always tries to access backed "127.0.0.1:8000"; you may need to adjust
[environment.js](https://github.com/papermerge/papermerge.js/blob/master/config/environment.js#L32).

**Comment by luyuanerp** [comment]
Thank you, run poetry run task worker according to your reply, the following error message is displayed, where should I change the configuration? I am using the cloud server public IP.

**Comment by ciur** [comment]
This (I mean starting worker with ``poetry run task worker``) is actually mentioned in the documentation:

https://docs.papermerge.io/Contributor%27s%20Manual/backend_dev_setup.html#worker
